#!/bin/sh

echo Update submodules ...
yadm submodule update --recursive --init

# Install emacs
git clone https://github.com/Riey/.emacs.d ~/.emacs.d

mkdir -pv ~/.vim/autoload
mkdir -pv ~/.local/share/nvim/site/autoload

ln -s ~/repos/vim-plug/plug.vim ~/.vim/autoload/plug.vim
ln -s ~/repos/vim-plug/plug.vim ~/.local/share/nvim/site/autoload/plug.vim

echo Install vim plugins ...
vim -c 'PlugInstall' -c 'qa!'

echo Install neovim plugins ...
nvim -c 'PlugInstall' -c 'CocInstall coc-rust-analyzer' -c 'qa!'

